services:
  backend:
    build:
      context: ./API-chatbot-langgraph
    container_name: fastapi-backend
    ports:
      - "8000:8000"
    volumes:
      - ./API-chatbot-langgraph:/app
    networks:
      - fullstack-network

  frontend:
    build:
      context: ./Chatbot-FE
    container_name: react-frontend
    ports:
      - "3000:3000"
    volumes:
      - ./Chatbot-FE:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
    stdin_open: true
    tty: true
    networks:
      - fullstack-network

  db:
    image: postgres:17
    container_name: postgres-db
    restart: always
    env_file: .env
    ports:
      - "5432:5432"
    volumes:
      - ./schema/supabase_backup.sql:/docker-entrypoint-initdb.d/supabase_backup.sql:ro
    networks:
      - fullstack-network

volumes:
  db:
    driver: local