services:
  backend:
    build:
      context: ./API-chatbot-langgraph
    container_name: fastapi-backend
    ports:
      - "8000:8000"
    volumes:
      - ./API-chatbot-langgraph:/app
    networks:
      - fullstack-network

  frontend:
    build:
      context: ./Chatbot-FE
    container_name: react-frontend
    ports:
      - "3000:3000"
    volumes:
      - ./Chatbot-FE:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
    stdin_open: true
    tty: true
    networks:
      - fullstack-network

networks:
  fullstack-network:
